# Delete index
# DELETE product-supplychain-consumer

curl -XDELETE "http://localhost:9200/product-supplychain-consumer"

# Create mapping for product-supplychain-consumer with age as integer and scan location as geo_point
# PUT product-supplychain-consumer/ {}
curl -XPUT "http://localhost:9200/product-supplychain-consumer/" -H 'Content-Type: application/json' -d'{    "mappings": {      "properties" : {        "age" : {          "type" : "integer"        },        "scan-location" : {          "type" : "nested",          "properties": {            "name": {"type": "text"},            "latlong" : {"type": "geo_point"}          }        },        "location": {          "type" : "geo_point"        },        "best-before-date" : {          "type" : "date"        },        "consumer id" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "device" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "gender" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "manufacturing-date" : {          "type" : "date"        },        "package" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "product" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "production-location" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "retail" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "size" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        },        "warehouse" : {          "type" : "text",          "fields" : {            "keyword" : {              "type" : "keyword",              "ignore_above" : 256            }          }        }      }    }}'

# Add some documents
# POST product-supplychain-consumer/_doc/1
curl -XPOST "http://localhost:9200/product-supplychain-consumer/_doc/1" -H 'Content-Type: application/json' -d'{"product":"Cola", "size": "1L", "package": "plastic", "manufacturing-date":"2019-05-18", "best-before-date":"2020-05-18", "production-location": "Houston", "warehouse":"Houston", "retail":"Oslo", "consumer id": "22", "age": "55", "gender": "F", "device":"Samsung", "scan-location": [ {"name": "Brisbane, Australia", "latlong": "59.913868,10.752245" } ], "location": "59.913868,10.752245" }'

curl -XPOST "http://localhost:9200/product-supplychain-consumer/_doc/2" -H 'Content-Type: application/json' -d'{"product":"Cola", "size": "1L", "package": "plastic", "manufacturing-date":"2019-05-18", "best-before-date":"2020-05-18", "production-location": "Houston", "warehouse":"Houston", "retail":"Oslo", "consumer id": "22", "age": "55", "gender": "F", "device":"Samsung", "scan-location": [ {"name": "Brisbane, Australia", "latlong": "59.913868,10.752245" } ], "location": "-27.469770,153.025131" }'

# TODO troubleshoot scan-location.latlong does not show on map
